"""202505050701am:resubmitting databases after deletion during security tests

Revision ID: 02ff96fb3f8a
Revises: 00acfdeb55ae
Create Date: 2025-05-05 07:03:06.414999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02ff96fb3f8a'
down_revision: Union[str, None] = '00acfdeb55ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
