"""202503140032am: added rating field to the Product Model

Revision ID: 0a045694c723
Revises: 78e60dc0b5af
Create Date: 2025-03-14 00:33:05.051349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a045694c723'
down_revision: Union[str, None] = '78e60dc0b5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
