"""202503140144am: change field name from 'image_url' to 'image' in product model in database_models.py

Revision ID: 1799b2f510f1
Revises: f1c4c49a0b5c
Create Date: 2025-03-14 01:44:40.935173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1799b2f510f1'
down_revision: Union[str, None] = 'f1c4c49a0b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'image')
    # ### end Alembic commands ###
