"""202504121608pm: Convert JSON to JSONB in OrderTracking model

Revision ID: 1b73151d0f9c
Revises: 550495f0581e
Create Date: 2025-04-12 16:12:55.813113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b73151d0f9c'
down_revision: Union[str, None] = '550495f0581e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
