"""202503101752pm:added more fields to conversationstate model..

Revision ID: 352d7be2194c
Revises: e911467d2c13
Create Date: 2025-03-10 17:53:01.599927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352d7be2194c'
down_revision: Union[str, None] = 'e911467d2c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
