"""202503140050am: removed stock field from the Product Model in database_models.py

Revision ID: 356fadb19671
Revises: 0a045694c723
Create Date: 2025-03-14 00:50:50.279951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356fadb19671'
down_revision: Union[str, None] = '0a045694c723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
