"""202504122105pm: ordertracking model

Revision ID: 447f396439d8
Revises: 3c58f860030e
Create Date: 2025-04-12 21:05:43.810618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '447f396439d8'
down_revision: Union[str, None] = '3c58f860030e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('order_tracking', 'user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               postgresql_using="user_id::integer")
    op.create_foreign_key(None, 'order_tracking', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_tracking', type_='foreignkey')
    op.alter_column('order_tracking', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
