"""202502280213am:added session_id column to cart model in database_models.py

Revision ID: 4bba73e67e2c
Revises: b91097c05157
Create Date: 2025-02-28 02:14:00.348533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bba73e67e2c'
down_revision: Union[str, None] = 'b91097c05157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('session_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'session_id')
    # ### end Alembic commands ###
