"""202504210239am: added orderhistory model to database_models.py

Revision ID: 5b6da9b8f465
Revises: be17d2daedda
Create Date: 2025-04-21 02:50:34.927781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6da9b8f465'
down_revision: Union[str, None] = 'be17d2daedda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_history', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('order_history', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index('ix_order_history_user_id_order_id', 'order_history', ['user_id', 'order_id'], unique=False)
    op.create_unique_constraint(None, 'order_history', ['order_id'])
    op.create_foreign_key(None, 'order_history', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_history', type_='foreignkey')
    op.drop_constraint(None, 'order_history', type_='unique')
    op.drop_index('ix_order_history_user_id_order_id', table_name='order_history')
    op.drop_column('order_history', 'updated_at')
    op.drop_column('order_history', 'created_at')
    # ### end Alembic commands ###
