"""202503090245am:shifted ConversationState model from response_models.py to database_models.py

Revision ID: 5f12e1bd0b96
Revises: eb0f33582fff
Create Date: 2025-03-09 02:46:08.222123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f12e1bd0b96'
down_revision: Union[str, None] = 'eb0f33582fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
