"""202503140106am: added cross field foreignkeys to connect Product Model and Cart Model in database_models.py

Revision ID: 6fbe614be7a7
Revises: c2240201da65
Create Date: 2025-03-14 01:06:53.268871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fbe614be7a7'
down_revision: Union[str, None] = 'c2240201da65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
