"""202503140025am: added attributes and image_url fields to the Product Model

Revision ID: 78e60dc0b5af
Revises: 5ebe0c1eee1a
Create Date: 2025-03-14 00:26:26.541475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78e60dc0b5af'
down_revision: Union[str, None] = '5ebe0c1eee1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('attributes', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'attributes')
    # ### end Alembic commands ###
