"""202503100220am:added current page in conversationstate model.

Revision ID: 89395b75cf92
Revises: 5f12e1bd0b96
Create Date: 2025-03-10 02:20:31.334097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89395b75cf92'
down_revision: Union[str, None] = '5f12e1bd0b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
