"""202503110117am:added 'items_per_page' field in conversationstate model

Revision ID: a175ecf3d05d
Revises: 352d7be2194c
Create Date: 2025-03-11 01:17:51.680234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a175ecf3d05d'
down_revision: Union[str, None] = '352d7be2194c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
