"""202504121608pm: Convert JSON to JSONB in OrderTracking model

Revision ID: b997b28a4758
Revises: 1b73151d0f9c
Create Date: 2025-04-12 16:16:00.776008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b997b28a4758'
down_revision: Union[str, None] = '1b73151d0f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
