"""202504110614am: added checkout model and other related models

Revision ID: b9e82a33be72
Revises: c8214c01cdd6
Create Date: 2025-04-11 06:14:58.157552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e82a33be72'
down_revision: Union[str, None] = 'c8214c01cdd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
