"""202504200218:added new model to database_models.py

Revision ID: be17d2daedda
Revises: b9d62e2daa76
Create Date: 2025-04-20 02:18:41.272950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be17d2daedda'
down_revision: Union[str, None] = 'b9d62e2daa76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
