"""202504121558pm: added ordertracking model

Revision ID: c1d2ed2933fb
Revises: 68b2763bd7f3
Create Date: 2025-04-12 15:58:53.647077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d2ed2933fb'
down_revision: Union[str, None] = '68b2763bd7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('carrier', sa.String(), nullable=True),
    sa.Column('carrier_api_key', sa.String(), nullable=True),
    sa.Column('tracking_numbers', sa.JSON(), nullable=True),
    sa.Column('delivery_instructions', sa.String(), nullable=True),
    sa.Column('geolocation_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_tracking')
    # ### end Alembic commands ###
