"""202503100220am:added current page in conversationstate model.

Revision ID: e911467d2c13
Revises: 89395b75cf92
Create Date: 2025-03-10 03:02:45.801581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e911467d2c13'
down_revision: Union[str, None] = '89395b75cf92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('user_message', sa.String(), nullable=True),
    sa.Column('bot_response', sa.String(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_ueser_interactions_id', table_name='ueser_interactions')
    op.drop_table('ueser_interactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ueser_interactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bot_response', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ueser_interactions_pkey')
    )
    op.create_index('ix_ueser_interactions_id', 'ueser_interactions', ['id'], unique=False)
    op.drop_table('user_interactions')
    # ### end Alembic commands ###
