"""202503090226am:just updating in case I forgot to update it

Revision ID: eb0f33582fff
Revises: 383c58a27bc4
Create Date: 2025-03-09 02:27:12.734716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0f33582fff'
down_revision: Union[str, None] = '383c58a27bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
